% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\author{}
\date{\vspace{-2.5em}}

\begin{document}

\section{Difference-in-Differences Analysis
Example}\label{difference-in-differences-analysis-example}

Reference: Callaway, Brantly and Pedro H.C. Sant'Anna.
``Difference-in-Differences with Multiple Time Periods.'' Journal of
Econometrics, Vol. 225, No.~2, pp.~200-230, 2021.
\url{https://doi.org/10.1016/j.jeconom.2020.12.001},
\url{https://arxiv.org/abs/1803.09015} R Package:
\url{https://cran.r-project.org/web/packages/did/index.html}

\subsection{Load Libraries}\label{load-libraries}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(did)}
\FunctionTok{library}\NormalTok{(tidyverse)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## -- Attaching packages --------------------------------------- tidyverse 1.3.2 --
## v ggplot2 3.4.0     v purrr   1.0.1
## v tibble  3.2.1     v dplyr   1.1.0
## v tidyr   1.3.0     v stringr 1.5.0
## v readr   2.1.3     v forcats 1.0.0
## -- Conflicts ------------------------------------------ tidyverse_conflicts() --
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(lubridate)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Attaching package: 'lubridate'
## 
## The following objects are masked from 'package:base':
## 
##     date, intersect, setdiff, union
\end{verbatim}

\subsection{Set Global variables}\label{set-global-variables}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{original\_file\_name }\OtherTok{\textless{}{-}} \StringTok{"/Users/ilyonsg/Documents/research/thesis/CB\_Lab\_Mapping\_Economic\_Migration/data/sl/nightlight\_values\_for\_csdind.csv"}
\NormalTok{clean\_monthly\_file\_name }\OtherTok{\textless{}{-}} \StringTok{"/Users/ilyonsg/Documents/research/thesis/CB\_Lab\_Mapping\_Economic\_Migration/data/sl/nightlight\_values\_for\_csdind\_nonames.csv"}
\NormalTok{clean\_yearly\_file\_name }\OtherTok{\textless{}{-}} \StringTok{"/Users/ilyonsg/Documents/research/thesis/CB\_Lab\_Mapping\_Economic\_Migration/data/sl/nightlight\_values\_for\_csdind\_years.csv"}
\end{Highlighting}
\end{Shaded}

\subsection{Clean up the Existing DF}\label{clean-up-the-existing-df}

Only need to run once to generate the data for the example.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# \# read in the data}
\CommentTok{\# df \textless{}{-} read\_csv(original\_file\_name)}
\CommentTok{\# glimpse(df)}

\CommentTok{\# \# drop the site\_name and extra image stats column}
\CommentTok{\# df \textless{}{-} df \%\textgreater{}\%}
\CommentTok{\#     select(}
\CommentTok{\#         {-}site\_name, }
\CommentTok{\#         {-}mean\_image\_value, }
\CommentTok{\#         {-}min\_image\_value, }
\CommentTok{\#         {-}max\_image\_value,}
\CommentTok{\#         {-}year\_commissioned,}
\CommentTok{\#         {-}year\_image,}
\CommentTok{\#         {-}month\_image,}
\CommentTok{\#         {-}month\_commissioned}
\CommentTok{\#     )}

\CommentTok{\# \# convert the site\_types not equal to "Control" to "Mini{-}grid"}
\CommentTok{\# df$site\_type[df$site\_type != "Control"] \textless{}{-} "Mini{-}grid"}

\CommentTok{\# \# rewrite the df to a csv}
\CommentTok{\# write\_csv(df, clean\_monthly\_file\_name)}
\end{Highlighting}
\end{Shaded}

\subsection{Read in the Data \&
Visualize}\label{read-in-the-data-visualize}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# read in the data}
\NormalTok{df }\OtherTok{\textless{}{-}} \FunctionTok{read\_csv}\NormalTok{(clean\_monthly\_file\_name)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Rows: 9945 Columns: 7
## -- Column specification --------------------------------------------------------
## Delimiter: ","
## chr  (1): site_type
## dbl  (4): image_value, site_id, group, time_period
## date (2): date_commissioned, image_date
## 
## i Use `spec()` to retrieve the full column specification for this data.
## i Specify the column types or set `show_col_types = FALSE` to quiet this message.
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# convert certain columns to factors}
\NormalTok{df}\SpecialCharTok{$}\NormalTok{site\_type }\OtherTok{\textless{}{-}} \FunctionTok{as.factor}\NormalTok{(df}\SpecialCharTok{$}\NormalTok{site\_type)}
\NormalTok{df}\SpecialCharTok{$}\NormalTok{site\_id }\OtherTok{\textless{}{-}} \FunctionTok{as.factor}\NormalTok{(df}\SpecialCharTok{$}\NormalTok{site\_id)}

\CommentTok{\# view data}
\FunctionTok{glimpse}\NormalTok{(df)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Rows: 9,945
## Columns: 7
## $ site_type         <fct> Control, Control, Control, Control, Control, Control~
## $ date_commissioned <date> 2013-12-01, 2013-12-01, 2013-12-01, 2013-12-01, 201~
## $ image_date        <date> 2014-01-01, 2014-01-01, 2014-01-01, 2014-01-01, 201~
## $ image_value       <dbl> 0.0081370871, 0.0319521341, 0.0101637386, 0.02598547~
## $ site_id           <fct> 61, 73, 83, 50, 64, 29, 12, 85, 26, 51, 36, 16, 2, 1~
## $ group             <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0~
## $ time_period       <dbl> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1~
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# visualize the image\_value over time with image\_date by grouped by site\_type}
\NormalTok{df }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ image\_date, }\AttributeTok{y =}\NormalTok{ image\_value, }\AttributeTok{color =}\NormalTok{ site\_type)) }\SpecialCharTok{+}
    \FunctionTok{geom\_point}\NormalTok{() }\SpecialCharTok{+}
    \FunctionTok{geom\_smooth}\NormalTok{() }\SpecialCharTok{+}
    \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Image Value Over Time by Site Type in Sierra Leone"}\NormalTok{, }\AttributeTok{x =} \StringTok{"Image Date"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Image Value"}\NormalTok{) }\SpecialCharTok{+}
    \FunctionTok{theme\_bw}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `geom_smooth()` using method = 'gam' and formula = 'y ~ s(x, bs = "cs")'
\end{verbatim}

\includegraphics{CSDinDExample_files/figure-latex/unnamed-chunk-4-1.pdf}

\subsection{Run the DinD Analysis with Months as Time
Periods}\label{run-the-dind-analysis-with-months-as-time-periods}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# read in the data}
\NormalTok{df }\OtherTok{\textless{}{-}} \FunctionTok{read\_csv}\NormalTok{(clean\_monthly\_file\_name)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Rows: 9945 Columns: 7
## -- Column specification --------------------------------------------------------
## Delimiter: ","
## chr  (1): site_type
## dbl  (4): image_value, site_id, group, time_period
## date (2): date_commissioned, image_date
## 
## i Use `spec()` to retrieve the full column specification for this data.
## i Specify the column types or set `show_col_types = FALSE` to quiet this message.
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# run the model}
\CommentTok{\# note these take about 30 seconds to run}
\CommentTok{\# https://bcallaway11.github.io/did/reference/att\_gt.html}
\NormalTok{did\_control }\OtherTok{\textless{}{-}} \FunctionTok{att\_gt}\NormalTok{(}
    \AttributeTok{yname =} \StringTok{"image\_value"}\NormalTok{, }\CommentTok{\# outcome variable}
    \AttributeTok{tname =} \StringTok{"time\_period"}\NormalTok{, }\CommentTok{\# time variable}
    \AttributeTok{idname =} \StringTok{"site\_id"}\NormalTok{, }\CommentTok{\# id variable}
    \AttributeTok{gname =} \StringTok{"group"}\NormalTok{, }\CommentTok{\# first treatment period variable}
    \AttributeTok{data =}\NormalTok{ df, }\CommentTok{\# data}
    \AttributeTok{control\_group =} \StringTok{"nevertreated"}\NormalTok{, }\CommentTok{\# set the comparison group as either "never treated" or "not yet treated"}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in pre_process_did(yname = yname, tname = tname, idname = idname, : Be aware that there are some small groups in your dataset.
##   Check groups: 67,69,72,73,77,78,82,86,89,90,91,98,100,101,102,104.
\end{verbatim}

\begin{verbatim}
## Warning in att_gt(yname = "image_value", tname = "time_period", idname =
## "site_id", : Not returning pre-test Wald statistic due to singular covariance
## matrix
\end{verbatim}

\begin{verbatim}
## Warning in att_gt(yname = "image_value", tname = "time_period", idname =
## "site_id", : Simultaneous critical value is arguably `too large' to be
## realible. This usually happens when number of observations per group is small
## and/or there is no much variation in outcomes.
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{did\_notyettreated }\OtherTok{\textless{}{-}} \FunctionTok{att\_gt}\NormalTok{(}
    \AttributeTok{yname =} \StringTok{"image\_value"}\NormalTok{, }\CommentTok{\# outcome variable}
    \AttributeTok{tname =} \StringTok{"time\_period"}\NormalTok{, }\CommentTok{\# time variable}
    \AttributeTok{idname =} \StringTok{"site\_id"}\NormalTok{, }\CommentTok{\# id variable}
    \AttributeTok{gname =} \StringTok{"group"}\NormalTok{, }\CommentTok{\# first treatment period variable}
    \AttributeTok{data =}\NormalTok{ df, }\CommentTok{\# data}
    \AttributeTok{control\_group =} \StringTok{"notyettreated"}\NormalTok{, }\CommentTok{\# set the comparison group as either "never treated" or "not yet treated"}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in pre_process_did(yname = yname, tname = tname, idname = idname, : Be aware that there are some small groups in your dataset.
##   Check groups: 67,69,72,73,77,78,82,86,89,90,91,98,100,101,102,104.
\end{verbatim}

\begin{verbatim}
## Warning in att_gt(yname = "image_value", tname = "time_period", idname =
## "site_id", : Not returning pre-test Wald statistic due to singular covariance
## matrix
\end{verbatim}

\begin{verbatim}
## Warning in att_gt(yname = "image_value", tname = "time_period", idname =
## "site_id", : Simultaneous critical value is arguably `too large' to be
## realible. This usually happens when number of observations per group is small
## and/or there is no much variation in outcomes.
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# view very long form of the results}
\CommentTok{\# summary(did\_control)}
\CommentTok{\# summary(did\_notyettreated)}

\CommentTok{\# aggregate the results}
\NormalTok{did\_control\_agg }\OtherTok{\textless{}{-}} \FunctionTok{aggte}\NormalTok{(}
\NormalTok{    did\_control,}
    \AttributeTok{type =} \StringTok{"dynamic"}\NormalTok{, }
    \AttributeTok{na.rm =} \ConstantTok{TRUE}
\NormalTok{)}

\NormalTok{did\_notyettreated\_agg }\OtherTok{\textless{}{-}} \FunctionTok{aggte}\NormalTok{(}
\NormalTok{    did\_notyettreated,}
    \AttributeTok{type =} \StringTok{"dynamic"}\NormalTok{, }
    \AttributeTok{na.rm =} \ConstantTok{TRUE}
\NormalTok{)}

\CommentTok{\# view the results}
\FunctionTok{summary}\NormalTok{(did\_control\_agg)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## aggte(MP = did_control, type = "dynamic", na.rm = TRUE)
## 
## Reference: Callaway, Brantly and Pedro H.C. Sant'Anna.  "Difference-in-Differences with Multiple Time Periods." Journal of Econometrics, Vol. 225, No. 2, pp. 200-230, 2021. <https://doi.org/10.1016/j.jeconom.2020.12.001>, <https://arxiv.org/abs/1803.09015> 
## 
## 
## Overall summary of ATT's based on event-study/dynamic aggregation:  
##      ATT    Std. Error     [ 95%  Conf. Int.] 
##  -0.0672        0.0509     -0.167      0.0325 
## 
## 
## Dynamic Effects:
##  Event time Estimate Std. Error [95% Simult.  Conf. Band] 
##        -102  -0.0769     0.0358       -0.1868      0.0330 
##        -101   0.0755     0.0359       -0.0348      0.1859 
##        -100   0.0481     0.0473       -0.0972      0.1934 
##         -99  -0.0578     0.0309       -0.1528      0.0372 
##         -98   0.0894     0.0743       -0.1389      0.3177 
##         -97  -0.0647     0.0822       -0.3173      0.1880 
##         -96   0.0404     0.0297       -0.0508      0.1316 
##         -95  -0.0228     0.0373       -0.1374      0.0919 
##         -94  -0.0284     0.0460       -0.1696      0.1128 
##         -93   0.0276     0.0282       -0.0591      0.1143 
##         -92  -0.0361     0.0222       -0.1042      0.0321 
##         -91   0.0386     0.0131       -0.0016      0.0788 
##         -90  -0.0015     0.0184       -0.0580      0.0550 
##         -89  -0.0123     0.0243       -0.0871      0.0625 
##         -88  -0.0002     0.0167       -0.0517      0.0512 
##         -87  -0.0070     0.0169       -0.0589      0.0449 
##         -86   0.0145     0.0145       -0.0300      0.0591 
##         -85   0.0028     0.0176       -0.0511      0.0568 
##         -84   0.0157     0.0275       -0.0688      0.1002 
##         -83  -0.0234     0.0249       -0.0998      0.0530 
##         -82   0.0106     0.0216       -0.0557      0.0770 
##         -81  -0.0374     0.0199       -0.0984      0.0236 
##         -80   0.0316     0.0217       -0.0351      0.0982 
##         -79   0.0211     0.0219       -0.0460      0.0883 
##         -78  -0.0107     0.0192       -0.0698      0.0484 
##         -77  -0.0007     0.0121       -0.0378      0.0364 
##         -76  -0.0343     0.0174       -0.0878      0.0191 
##         -75   0.0444     0.0186       -0.0128      0.1016 
##         -74  -0.0384     0.0195       -0.0984      0.0216 
##         -73   0.0168     0.0202       -0.0453      0.0789 
##         -72   0.0108     0.0174       -0.0426      0.0643 
##         -71   0.0006     0.0122       -0.0367      0.0380 
##         -70  -0.0003     0.0182       -0.0562      0.0555 
##         -69  -0.0082     0.0144       -0.0524      0.0359 
##         -68   0.0437     0.0359       -0.0665      0.1540 
##         -67  -0.0077     0.0350       -0.1153      0.0998 
##         -66  -0.0216     0.0288       -0.1102      0.0670 
##         -65   0.0047     0.0110       -0.0292      0.0386 
##         -64  -0.0117     0.0158       -0.0603      0.0369 
##         -63  -0.0202     0.0204       -0.0830      0.0426 
##         -62   0.0515     0.0179       -0.0035      0.1064 
##         -61  -0.0341     0.0139       -0.0768      0.0086 
##         -60  -0.0021     0.0117       -0.0380      0.0338 
##         -59   0.0177     0.0124       -0.0204      0.0558 
##         -58   0.0072     0.0154       -0.0400      0.0545 
##         -57  -0.0194     0.0142       -0.0631      0.0244 
##         -56  -0.0010     0.0098       -0.0311      0.0291 
##         -55   0.0199     0.0132       -0.0206      0.0604 
##         -54  -0.0088     0.0108       -0.0419      0.0242 
##         -53  -0.0293     0.0097       -0.0591      0.0004 
##         -52   0.0370     0.0166       -0.0141      0.0880 
##         -51  -0.0217     0.0170       -0.0741      0.0307 
##         -50   0.0027     0.0106       -0.0299      0.0352 
##         -49   0.0549     0.0249       -0.0217      0.1314 
##         -48  -0.0079     0.0323       -0.1071      0.0914 
##         -47   0.0039     0.0357       -0.1057      0.1135 
##         -46  -0.0369     0.0232       -0.1082      0.0344 
##         -45  -0.0280     0.0111       -0.0620      0.0060 
##         -44   0.0312     0.0121       -0.0060      0.0685 
##         -43  -0.0151     0.0122       -0.0525      0.0222 
##         -42   0.0064     0.0123       -0.0313      0.0442 
##         -41  -0.0072     0.0124       -0.0453      0.0308 
##         -40   0.0152     0.0154       -0.0321      0.0624 
##         -39  -0.0002     0.0128       -0.0395      0.0390 
##         -38   0.0073     0.0091       -0.0208      0.0353 
##         -37   0.0056     0.0112       -0.0288      0.0400 
##         -36  -0.0055     0.0137       -0.0475      0.0366 
##         -35   0.0161     0.0221       -0.0518      0.0841 
##         -34  -0.0099     0.0274       -0.0940      0.0743 
##         -33   0.0267     0.0278       -0.0587      0.1121 
##         -32  -0.0229     0.0239       -0.0963      0.0505 
##         -31   0.0004     0.0144       -0.0437      0.0445 
##         -30  -0.0163     0.0109       -0.0498      0.0171 
##         -29  -0.0084     0.0101       -0.0393      0.0225 
##         -28   0.0048     0.0114       -0.0302      0.0397 
##         -27  -0.0010     0.0085       -0.0272      0.0252 
##         -26   0.0039     0.0088       -0.0231      0.0309 
##         -25  -0.0209     0.0200       -0.0823      0.0404 
##         -24   0.0306     0.0217       -0.0361      0.0973 
##         -23  -0.0202     0.0102       -0.0516      0.0111 
##         -22   0.0350     0.0158       -0.0136      0.0837 
##         -21   0.0059     0.0317       -0.0914      0.1033 
##         -20  -0.0034     0.0290       -0.0926      0.0858 
##         -19  -0.0148     0.0141       -0.0582      0.0286 
##         -18  -0.0007     0.0180       -0.0560      0.0547 
##         -17  -0.0009     0.0114       -0.0360      0.0342 
##         -16   0.0054     0.0102       -0.0259      0.0368 
##         -15  -0.0057     0.0154       -0.0530      0.0415 
##         -14   0.0289     0.0252       -0.0484      0.1061 
##         -13   0.0112     0.0259       -0.0683      0.0907 
##         -12  -0.0507     0.0243       -0.1252      0.0238 
##         -11   0.0323     0.0245       -0.0430      0.1076 
##         -10  -0.0054     0.0223       -0.0739      0.0632 
##          -9  -0.0045     0.0272       -0.0881      0.0790 
##          -8   0.0038     0.0165       -0.0470      0.0545 
##          -7  -0.0029     0.0168       -0.0546      0.0489 
##          -6   0.0101     0.0189       -0.0481      0.0682 
##          -5  -0.0158     0.0113       -0.0506      0.0189 
##          -4  -0.0157     0.0095       -0.0447      0.0134 
##          -3   0.0050     0.0115       -0.0303      0.0403 
##          -2   0.0046     0.0120       -0.0323      0.0414 
##          -1   0.0070     0.0264       -0.0740      0.0881 
##           0  -0.0029     0.0271       -0.0862      0.0805 
##           1  -0.0019     0.0311       -0.0975      0.0937 
##           2  -0.0056     0.0261       -0.0858      0.0745 
##           3  -0.0198     0.0265       -0.1013      0.0616 
##           4   0.0140     0.0262       -0.0665      0.0944 
##           5   0.0001     0.0261       -0.0800      0.0802 
##           6   0.0075     0.0255       -0.0707      0.0857 
##           7  -0.0171     0.0302       -0.1101      0.0758 
##           8   0.0038     0.0280       -0.0823      0.0899 
##           9   0.0193     0.0297       -0.0719      0.1106 
##          10   0.0166     0.0296       -0.0744      0.1077 
##          11   0.0429     0.0301       -0.0495      0.1353 
##          12   0.0316     0.0295       -0.0591      0.1224 
##          13   0.0080     0.0290       -0.0812      0.0972 
##          14   0.0072     0.0322       -0.0917      0.1061 
##          15  -0.0217     0.0279       -0.1075      0.0641 
##          16  -0.0189     0.0227       -0.0888      0.0509 
##          17  -0.0416     0.0242       -0.1160      0.0327 
##          18  -0.0165     0.0242       -0.0908      0.0578 
##          19  -0.0182     0.0261       -0.0985      0.0621 
##          20  -0.0090     0.0249       -0.0854      0.0675 
##          21  -0.0668     0.0288       -0.1553      0.0217 
##          22   0.0086     0.0295       -0.0820      0.0992 
##          23   0.0026     0.0238       -0.0706      0.0759 
##          24   0.0176     0.0228       -0.0526      0.0877 
##          25   0.0063     0.0261       -0.0738      0.0865 
##          26  -0.0159     0.0319       -0.1141      0.0823 
##          27  -0.0456     0.0284       -0.1329      0.0416 
##          28  -0.0127     0.0317       -0.1101      0.0847 
##          29  -0.0232     0.0253       -0.1010      0.0546 
##          30  -0.0457     0.0356       -0.1550      0.0637 
##          31  -0.0133     0.0317       -0.1107      0.0841 
##          32  -0.0344     0.0363       -0.1459      0.0771 
##          33  -0.0455     0.0570       -0.2208      0.1298 
##          34   0.0017     0.0337       -0.1018      0.1052 
##          35  -0.0159     0.0304       -0.1094      0.0775 
##          36  -0.0333     0.0431       -0.1659      0.0992 
##          37  -0.0233     0.0376       -0.1389      0.0922 
##          38  -0.0663     0.0400       -0.1892      0.0566 
##          39  -0.0360     0.0364       -0.1478      0.0758 
##          40  -0.0498     0.0405       -0.1741      0.0745 
##          41  -0.0512     0.0385       -0.1694      0.0670 
##          42  -0.0419     0.0432       -0.1745      0.0907 
##          43  -0.0370     0.0451       -0.1755      0.1015 
##          44  -0.0469     0.0380       -0.1639      0.0700 
##          45  -0.0281     0.0520       -0.1880      0.1318 
##          46  -0.0328     0.0471       -0.1777      0.1121 
##          47  -0.0102     0.0548       -0.1785      0.1580 
##          48  -0.1047     0.1057       -0.4294      0.2201 
##          49  -0.1001     0.1094       -0.4361      0.2360 
##          50  -0.0629     0.1152       -0.4170      0.2911 
##          51  -0.1931     0.1265       -0.5819      0.1958 
##          52  -0.3235     0.1297       -0.7220      0.0751 
##          53  -0.3405     0.1158       -0.6963      0.0153 
##          54  -0.1875     0.1227       -0.5644      0.1895 
##          55  -0.1853     0.1071       -0.5145      0.1439 
##          56  -0.1911     0.1192       -0.5575      0.1752 
##          57  -0.1952     0.1128       -0.5419      0.1515 
##          58  -0.1979     0.1101       -0.5361      0.1403 
##          59  -0.1944     0.1197       -0.5621      0.1732 
##          60  -0.0937     0.1247       -0.4768      0.2894 
##          61  -0.2643     0.1148       -0.6170      0.0883 
##          62  -0.2434     0.1205       -0.6138      0.1269 
##          63  -0.1837     0.1070       -0.5126      0.1453 
##          64  -0.2630     0.1239       -0.6436      0.1176 
##          65  -0.2205     0.1763       -0.7621      0.3211 
##          66  -0.1978     0.1233       -0.5766      0.1810 
## ---
## Signif. codes: `*' confidence band does not cover 0
## 
## Control Group:  Never Treated,  Anticipation Periods:  0
## Estimation Method:  Doubly Robust
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(did\_notyettreated\_agg)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## aggte(MP = did_notyettreated, type = "dynamic", na.rm = TRUE)
## 
## Reference: Callaway, Brantly and Pedro H.C. Sant'Anna.  "Difference-in-Differences with Multiple Time Periods." Journal of Econometrics, Vol. 225, No. 2, pp. 200-230, 2021. <https://doi.org/10.1016/j.jeconom.2020.12.001>, <https://arxiv.org/abs/1803.09015> 
## 
## 
## Overall summary of ATT's based on event-study/dynamic aggregation:  
##      ATT    Std. Error     [ 95%  Conf. Int.] 
##  -0.0681        0.0498    -0.1656      0.0294 
## 
## 
## Dynamic Effects:
##  Event time Estimate Std. Error [95% Simult.  Conf. Band]  
##        -102  -0.0771     0.0219       -0.1448     -0.0095 *
##        -101   0.0352     0.0259       -0.0448      0.1152  
##        -100   0.0682     0.0581       -0.1113      0.2477  
##         -99  -0.0688     0.0269       -0.1520      0.0145  
##         -98   0.0860     0.0823       -0.1682      0.3403  
##         -97  -0.0685     0.0866       -0.3360      0.1991  
##         -96   0.0538     0.0304       -0.0400      0.1477  
##         -95  -0.0367     0.0436       -0.1713      0.0979  
##         -94  -0.0192     0.0424       -0.1503      0.1120  
##         -93   0.0265     0.0284       -0.0611      0.1142  
##         -92  -0.0337     0.0171       -0.0866      0.0192  
##         -91   0.0373     0.0122       -0.0006      0.0751  
##         -90   0.0017     0.0245       -0.0739      0.0773  
##         -89  -0.0191     0.0217       -0.0862      0.0481  
##         -88  -0.0048     0.0140       -0.0480      0.0383  
##         -87  -0.0097     0.0172       -0.0628      0.0434  
##         -86   0.0100     0.0139       -0.0329      0.0529  
##         -85  -0.0059     0.0192       -0.0651      0.0533  
##         -84   0.0259     0.0297       -0.0659      0.1177  
##         -83  -0.0264     0.0230       -0.0974      0.0446  
##         -82   0.0151     0.0233       -0.0570      0.0872  
##         -81  -0.0389     0.0206       -0.1024      0.0247  
##         -80   0.0353     0.0184       -0.0215      0.0921  
##         -79   0.0136     0.0209       -0.0509      0.0782  
##         -78  -0.0042     0.0181       -0.0603      0.0518  
##         -77  -0.0042     0.0106       -0.0370      0.0286  
##         -76  -0.0299     0.0149       -0.0759      0.0161  
##         -75   0.0389     0.0181       -0.0169      0.0947  
##         -74  -0.0385     0.0183       -0.0950      0.0181  
##         -73   0.0112     0.0195       -0.0489      0.0714  
##         -72   0.0130     0.0174       -0.0407      0.0666  
##         -71   0.0011     0.0115       -0.0345      0.0366  
##         -70  -0.0016     0.0169       -0.0538      0.0506  
##         -69  -0.0075     0.0132       -0.0484      0.0335  
##         -68   0.0412     0.0345       -0.0655      0.1480  
##         -67  -0.0148     0.0388       -0.1346      0.1050  
##         -66  -0.0182     0.0284       -0.1061      0.0696  
##         -65   0.0097     0.0115       -0.0257      0.0451  
##         -64  -0.0167     0.0158       -0.0656      0.0322  
##         -63  -0.0142     0.0196       -0.0748      0.0463  
##         -62   0.0495     0.0165       -0.0014      0.1004  
##         -61  -0.0362     0.0145       -0.0809      0.0086  
##         -60   0.0001     0.0116       -0.0357      0.0358  
##         -59   0.0185     0.0107       -0.0146      0.0516  
##         -58   0.0066     0.0145       -0.0381      0.0512  
##         -57  -0.0179     0.0157       -0.0663      0.0305  
##         -56  -0.0066     0.0097       -0.0367      0.0235  
##         -55   0.0168     0.0132       -0.0240      0.0575  
##         -54  -0.0095     0.0106       -0.0422      0.0232  
##         -53  -0.0285     0.0102       -0.0599      0.0028  
##         -52   0.0375     0.0143       -0.0068      0.0817  
##         -51  -0.0238     0.0187       -0.0816      0.0340  
##         -50   0.0035     0.0108       -0.0298      0.0368  
##         -49   0.0588     0.0238       -0.0147      0.1323  
##         -48  -0.0111     0.0317       -0.1091      0.0869  
##         -47   0.0064     0.0352       -0.1023      0.1151  
##         -46  -0.0400     0.0255       -0.1187      0.0387  
##         -45  -0.0234     0.0104       -0.0556      0.0087  
##         -44   0.0266     0.0119       -0.0103      0.0635  
##         -43  -0.0137     0.0126       -0.0526      0.0252  
##         -42   0.0052     0.0116       -0.0308      0.0411  
##         -41  -0.0064     0.0128       -0.0459      0.0331  
##         -40   0.0111     0.0142       -0.0326      0.0549  
##         -39   0.0013     0.0117       -0.0347      0.0374  
##         -38   0.0042     0.0087       -0.0227      0.0311  
##         -37   0.0076     0.0112       -0.0271      0.0423  
##         -36  -0.0103     0.0129       -0.0501      0.0295  
##         -35   0.0192     0.0230       -0.0519      0.0904  
##         -34  -0.0107     0.0276       -0.0960      0.0746  
##         -33   0.0254     0.0279       -0.0608      0.1116  
##         -32  -0.0266     0.0271       -0.1103      0.0571  
##         -31  -0.0002     0.0130       -0.0403      0.0399  
##         -30  -0.0149     0.0109       -0.0485      0.0187  
##         -29  -0.0013     0.0089       -0.0288      0.0261  
##         -28   0.0032     0.0118       -0.0332      0.0397  
##         -27  -0.0033     0.0089       -0.0308      0.0242  
##         -26   0.0065     0.0094       -0.0227      0.0357  
##         -25  -0.0250     0.0199       -0.0865      0.0364  
##         -24   0.0292     0.0216       -0.0377      0.0960  
##         -23  -0.0164     0.0092       -0.0449      0.0121  
##         -22   0.0339     0.0170       -0.0186      0.0864  
##         -21   0.0060     0.0313       -0.0907      0.1027  
##         -20  -0.0124     0.0313       -0.1090      0.0842  
##         -19  -0.0128     0.0156       -0.0611      0.0354  
##         -18   0.0028     0.0169       -0.0493      0.0549  
##         -17  -0.0035     0.0120       -0.0405      0.0335  
##         -16   0.0038     0.0100       -0.0269      0.0346  
##         -15  -0.0066     0.0157       -0.0551      0.0419  
##         -14   0.0280     0.0251       -0.0495      0.1056  
##         -13   0.0090     0.0253       -0.0691      0.0871  
##         -12  -0.0497     0.0225       -0.1193      0.0199  
##         -11   0.0374     0.0240       -0.0369      0.1117  
##         -10  -0.0027     0.0241       -0.0772      0.0717  
##          -9  -0.0019     0.0253       -0.0801      0.0764  
##          -8  -0.0022     0.0175       -0.0562      0.0519  
##          -7  -0.0060     0.0177       -0.0606      0.0485  
##          -6   0.0095     0.0196       -0.0511      0.0701  
##          -5  -0.0166     0.0107       -0.0497      0.0166  
##          -4  -0.0139     0.0089       -0.0415      0.0138  
##          -3   0.0078     0.0114       -0.0276      0.0432  
##          -2   0.0040     0.0118       -0.0325      0.0406  
##          -1   0.0024     0.0289       -0.0869      0.0917  
##           0  -0.0025     0.0262       -0.0834      0.0784  
##           1  -0.0010     0.0276       -0.0864      0.0843  
##           2   0.0005     0.0285       -0.0875      0.0885  
##           3  -0.0154     0.0267       -0.0981      0.0672  
##           4   0.0151     0.0249       -0.0617      0.0919  
##           5  -0.0021     0.0269       -0.0852      0.0811  
##           6   0.0042     0.0262       -0.0768      0.0852  
##           7  -0.0199     0.0323       -0.1198      0.0800  
##           8   0.0095     0.0265       -0.0726      0.0915  
##           9   0.0250     0.0300       -0.0678      0.1177  
##          10   0.0210     0.0309       -0.0744      0.1163  
##          11   0.0413     0.0273       -0.0429      0.1256  
##          12   0.0327     0.0264       -0.0488      0.1142  
##          13   0.0073     0.0285       -0.0809      0.0955  
##          14   0.0078     0.0334       -0.0954      0.1109  
##          15  -0.0189     0.0275       -0.1039      0.0661  
##          16  -0.0183     0.0243       -0.0934      0.0567  
##          17  -0.0416     0.0236       -0.1144      0.0311  
##          18  -0.0163     0.0230       -0.0874      0.0547  
##          19  -0.0170     0.0241       -0.0916      0.0576  
##          20  -0.0117     0.0267       -0.0943      0.0708  
##          21  -0.0670     0.0273       -0.1514      0.0175  
##          22   0.0089     0.0292       -0.0814      0.0992  
##          23  -0.0022     0.0227       -0.0722      0.0679  
##          24   0.0103     0.0246       -0.0656      0.0862  
##          25   0.0000     0.0271       -0.0838      0.0839  
##          26  -0.0196     0.0321       -0.1189      0.0798  
##          27  -0.0498     0.0284       -0.1374      0.0378  
##          28  -0.0113     0.0312       -0.1078      0.0852  
##          29  -0.0245     0.0234       -0.0968      0.0477  
##          30  -0.0507     0.0364       -0.1633      0.0619  
##          31  -0.0189     0.0320       -0.1177      0.0800  
##          32  -0.0383     0.0370       -0.1526      0.0759  
##          33  -0.0451     0.0520       -0.2057      0.1155  
##          34   0.0029     0.0324       -0.0974      0.1031  
##          35  -0.0158     0.0288       -0.1048      0.0733  
##          36  -0.0335     0.0432       -0.1670      0.1000  
##          37  -0.0252     0.0373       -0.1406      0.0902  
##          38  -0.0690     0.0428       -0.2012      0.0633  
##          39  -0.0367     0.0358       -0.1472      0.0739  
##          40  -0.0507     0.0427       -0.1826      0.0812  
##          41  -0.0492     0.0363       -0.1614      0.0630  
##          42  -0.0442     0.0440       -0.1801      0.0916  
##          43  -0.0414     0.0481       -0.1900      0.1071  
##          44  -0.0517     0.0434       -0.1858      0.0825  
##          45  -0.0306     0.0571       -0.2072      0.1460  
##          46  -0.0368     0.0488       -0.1874      0.1139  
##          47  -0.0126     0.0506       -0.1689      0.1437  
##          48  -0.1078     0.0955       -0.4028      0.1873  
##          49  -0.1029     0.1197       -0.4728      0.2670  
##          50  -0.0696     0.1113       -0.4134      0.2742  
##          51  -0.2090     0.1338       -0.6224      0.2045  
##          52  -0.3130     0.1208       -0.6862      0.0602  
##          53  -0.3405     0.1115       -0.6852      0.0041  
##          54  -0.1875     0.1393       -0.6180      0.2430  
##          55  -0.1853     0.1017       -0.4997      0.1291  
##          56  -0.1911     0.1224       -0.5695      0.1872  
##          57  -0.1952     0.1157       -0.5527      0.1624  
##          58  -0.1979     0.1179       -0.5622      0.1664  
##          59  -0.1944     0.1238       -0.5771      0.1882  
##          60  -0.0937     0.1222       -0.4714      0.2840  
##          61  -0.2643     0.1228       -0.6437      0.1151  
##          62  -0.2434     0.1157       -0.6009      0.1140  
##          63  -0.1837     0.1102       -0.5243      0.1570  
##          64  -0.2630     0.1306       -0.6667      0.1407  
##          65  -0.2205     0.1828       -0.7853      0.3443  
##          66  -0.1978     0.1304       -0.6008      0.2052  
## ---
## Signif. codes: `*' confidence band does not cover 0
## 
## Control Group:  Not Yet Treated,  Anticipation Periods:  0
## Estimation Method:  Doubly Robust
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# plot group{-}time ATTs}
\NormalTok{did\_control\_agg\_plt }\OtherTok{\textless{}{-}} \FunctionTok{ggdid}\NormalTok{(did\_control\_agg) }\SpecialCharTok{+}
    \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Group{-}Time ATTs for Control Group"}\NormalTok{, }\AttributeTok{x =} \StringTok{"Time Period"}\NormalTok{, }\AttributeTok{y =} \StringTok{"ATT"}\NormalTok{) }\SpecialCharTok{+}
    \FunctionTok{theme\_bw}\NormalTok{() }\SpecialCharTok{+}
    \FunctionTok{theme}\NormalTok{(}\AttributeTok{axis.text.x =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{angle =} \DecValTok{90}\NormalTok{, }\AttributeTok{vjust =} \FloatTok{0.5}\NormalTok{, }\AttributeTok{hjust =} \DecValTok{1}\NormalTok{))}

\NormalTok{did\_notyettreated\_agg\_plt }\OtherTok{\textless{}{-}} \FunctionTok{ggdid}\NormalTok{(did\_notyettreated\_agg) }\SpecialCharTok{+}
    \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Group{-}Time ATTs for Not Yet Treated Group"}\NormalTok{, }\AttributeTok{x =} \StringTok{"Time Period"}\NormalTok{, }\AttributeTok{y =} \StringTok{"ATT"}\NormalTok{) }\SpecialCharTok{+}
    \FunctionTok{theme\_bw}\NormalTok{() }\SpecialCharTok{+} 
    \FunctionTok{theme}\NormalTok{(}\AttributeTok{axis.text.x =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{angle =} \DecValTok{90}\NormalTok{, }\AttributeTok{vjust =} \FloatTok{0.5}\NormalTok{, }\AttributeTok{hjust =} \DecValTok{1}\NormalTok{))}

\FunctionTok{print}\NormalTok{(did\_control\_agg\_plt)}
\end{Highlighting}
\end{Shaded}

\includegraphics{CSDinDExample_files/figure-latex/unnamed-chunk-5-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(did\_notyettreated\_agg\_plt)}
\end{Highlighting}
\end{Shaded}

\includegraphics{CSDinDExample_files/figure-latex/unnamed-chunk-5-2.pdf}

\subsection{Results of Monthly
Analysis}\label{results-of-monthly-analysis}

\subsubsection{Control Group}\label{control-group}

Overall summary of ATT's based on event-study/dynamic aggregation:\\
ATT Std. Error {[} 95\% Conf. Int.{]} -0.0672 0.0514 -0.1679 0.0334

\subsubsection{Not Yet Treated Group}\label{not-yet-treated-group}

Overall summary of ATT's based on event-study/dynamic aggregation:\\
ATT Std. Error {[} 95\% Conf. Int.{]} -0.0681 0.0515 -0.1691 0.0328

\subsection{Aggregate Data into Yearly Periods instead of Monthly
Periods}\label{aggregate-data-into-yearly-periods-instead-of-monthly-periods}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# read in the data}
\NormalTok{df }\OtherTok{\textless{}{-}} \FunctionTok{read\_csv}\NormalTok{(clean\_monthly\_file\_name)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Rows: 9945 Columns: 7
## -- Column specification --------------------------------------------------------
## Delimiter: ","
## chr  (1): site_type
## dbl  (4): image_value, site_id, group, time_period
## date (2): date_commissioned, image_date
## 
## i Use `spec()` to retrieve the full column specification for this data.
## i Specify the column types or set `show_col_types = FALSE` to quiet this message.
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# convert certain columns to factors}
\NormalTok{df}\SpecialCharTok{$}\NormalTok{site\_type }\OtherTok{\textless{}{-}} \FunctionTok{as.factor}\NormalTok{(df}\SpecialCharTok{$}\NormalTok{site\_type)}
\NormalTok{df}\SpecialCharTok{$}\NormalTok{site\_id }\OtherTok{\textless{}{-}} \FunctionTok{as.factor}\NormalTok{(df}\SpecialCharTok{$}\NormalTok{site\_id)}

\CommentTok{\# view data}
\FunctionTok{glimpse}\NormalTok{(df)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Rows: 9,945
## Columns: 7
## $ site_type         <fct> Control, Control, Control, Control, Control, Control~
## $ date_commissioned <date> 2013-12-01, 2013-12-01, 2013-12-01, 2013-12-01, 201~
## $ image_date        <date> 2014-01-01, 2014-01-01, 2014-01-01, 2014-01-01, 201~
## $ image_value       <dbl> 0.0081370871, 0.0319521341, 0.0101637386, 0.02598547~
## $ site_id           <fct> 61, 73, 83, 50, 64, 29, 12, 85, 26, 51, 36, 16, 2, 1~
## $ group             <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0~
## $ time_period       <dbl> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1~
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# add in year\_image and year\_commissioned}
\NormalTok{df}\SpecialCharTok{$}\NormalTok{year\_image }\OtherTok{\textless{}{-}} \FunctionTok{year}\NormalTok{(df}\SpecialCharTok{$}\NormalTok{image\_date)}
\NormalTok{df}\SpecialCharTok{$}\NormalTok{year\_commissioned }\OtherTok{\textless{}{-}} \FunctionTok{year}\NormalTok{(df}\SpecialCharTok{$}\NormalTok{date\_commissioned)}

\CommentTok{\# take the mean image value for each site for each year}
\NormalTok{df }\OtherTok{\textless{}{-}}\NormalTok{ df }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{group\_by}\NormalTok{(site\_id, site\_type, year\_image, year\_commissioned) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{summarize}\NormalTok{(}
        \AttributeTok{image\_value\_mean =} \FunctionTok{mean}\NormalTok{(image\_value),}
        \AttributeTok{image\_value\_median =} \FunctionTok{median}\NormalTok{(image\_value)}
\NormalTok{    )}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `summarise()` has grouped output by 'site_id', 'site_type', 'year_image'. You
## can override using the `.groups` argument.
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{glimpse}\NormalTok{(df)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Rows: 850
## Columns: 6
## Groups: site_id, site_type, year_image [850]
## $ site_id            <fct> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, ~
## $ site_type          <fct> Mini-grid, Mini-grid, Mini-grid, Mini-grid, Mini-gr~
## $ year_image         <dbl> 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 202~
## $ year_commissioned  <dbl> 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 201~
## $ image_value_mean   <dbl> 0.16127321, 0.18979563, 0.05666013, 0.32951296, 0.2~
## $ image_value_median <dbl> 0.09292889, 0.09532469, 0.06066093, 0.31228186, 0.2~
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{start\_year }\OtherTok{\textless{}{-}} \FunctionTok{min}\NormalTok{(df}\SpecialCharTok{$}\NormalTok{year\_image)}

\CommentTok{\# create group variable, controls are 0}
\NormalTok{df}\SpecialCharTok{$}\NormalTok{group }\OtherTok{\textless{}{-}}\NormalTok{ df}\SpecialCharTok{$}\NormalTok{year\_commissioned }\SpecialCharTok{{-}}\NormalTok{ start\_year }\SpecialCharTok{+} \DecValTok{1}

\CommentTok{\# add a time period variable which is year\_image {-} start\_year, start year is 1}
\NormalTok{df}\SpecialCharTok{$}\NormalTok{time\_period }\OtherTok{\textless{}{-}}\NormalTok{ df}\SpecialCharTok{$}\NormalTok{year\_image }\SpecialCharTok{{-}}\NormalTok{ start\_year }\SpecialCharTok{+} \DecValTok{1}

\CommentTok{\# glimpse the head}
\FunctionTok{glimpse}\NormalTok{(df)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Rows: 850
## Columns: 8
## Groups: site_id, site_type, year_image [850]
## $ site_id            <fct> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, ~
## $ site_type          <fct> Mini-grid, Mini-grid, Mini-grid, Mini-grid, Mini-gr~
## $ year_image         <dbl> 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 202~
## $ year_commissioned  <dbl> 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 201~
## $ image_value_mean   <dbl> 0.16127321, 0.18979563, 0.05666013, 0.32951296, 0.2~
## $ image_value_median <dbl> 0.09292889, 0.09532469, 0.06066093, 0.31228186, 0.2~
## $ group              <dbl> 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, ~
## $ time_period        <dbl> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7,~
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# export df to csv}
\FunctionTok{write\_csv}\NormalTok{(df, clean\_yearly\_file\_name)}
\end{Highlighting}
\end{Shaded}

\subsection{Rerun the Analysis}\label{rerun-the-analysis}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# read in the data}
\NormalTok{df }\OtherTok{\textless{}{-}} \FunctionTok{read\_csv}\NormalTok{(clean\_yearly\_file\_name)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Rows: 850 Columns: 8
## -- Column specification --------------------------------------------------------
## Delimiter: ","
## chr (1): site_type
## dbl (7): site_id, year_image, year_commissioned, image_value_mean, image_val...
## 
## i Use `spec()` to retrieve the full column specification for this data.
## i Specify the column types or set `show_col_types = FALSE` to quiet this message.
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# run the model}
\CommentTok{\# https://bcallaway11.github.io/did/reference/att\_gt.html}
\NormalTok{did\_control }\OtherTok{\textless{}{-}} \FunctionTok{att\_gt}\NormalTok{(}
    \AttributeTok{yname =} \StringTok{"image\_value\_median"}\NormalTok{, }\CommentTok{\# outcome variable}
    \AttributeTok{tname =} \StringTok{"time\_period"}\NormalTok{, }\CommentTok{\# time variable}
    \AttributeTok{idname =} \StringTok{"site\_id"}\NormalTok{, }\CommentTok{\# id variable}
    \AttributeTok{gname =} \StringTok{"group"}\NormalTok{, }\CommentTok{\# first treatment period variable}
    \AttributeTok{data =}\NormalTok{ df, }\CommentTok{\# data}
    \AttributeTok{control\_group =} \StringTok{"nevertreated"}\NormalTok{, }\CommentTok{\# set the comparison group as either "never treated" or "not yet treated"}
\NormalTok{)}

\NormalTok{did\_notyettreated }\OtherTok{\textless{}{-}} \FunctionTok{att\_gt}\NormalTok{(}
    \AttributeTok{yname =} \StringTok{"image\_value\_median"}\NormalTok{, }\CommentTok{\# outcome variable}
    \AttributeTok{tname =} \StringTok{"time\_period"}\NormalTok{, }\CommentTok{\# time variable}
    \AttributeTok{idname =} \StringTok{"site\_id"}\NormalTok{, }\CommentTok{\# id variable}
    \AttributeTok{gname =} \StringTok{"group"}\NormalTok{, }\CommentTok{\# first treatment period variable}
    \AttributeTok{data =}\NormalTok{ df, }\CommentTok{\# data}
    \AttributeTok{control\_group =} \StringTok{"notyettreated"}\NormalTok{, }\CommentTok{\# set the comparison group as either "never treated" or "not yet treated"}
\NormalTok{)}
\CommentTok{\# no warnings this time!}

\CommentTok{\# aggregate the results}
\NormalTok{did\_control\_agg }\OtherTok{\textless{}{-}} \FunctionTok{aggte}\NormalTok{(}
\NormalTok{    did\_control,}
    \AttributeTok{type =} \StringTok{"dynamic"}\NormalTok{, }
    \AttributeTok{na.rm =} \ConstantTok{TRUE}
\NormalTok{)}

\NormalTok{did\_notyettreated\_agg }\OtherTok{\textless{}{-}} \FunctionTok{aggte}\NormalTok{(}
\NormalTok{    did\_notyettreated,}
    \AttributeTok{type =} \StringTok{"dynamic"}\NormalTok{, }
    \AttributeTok{na.rm =} \ConstantTok{TRUE}
\NormalTok{)}

\CommentTok{\# view the results}
\FunctionTok{summary}\NormalTok{(did\_control\_agg)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## aggte(MP = did_control, type = "dynamic", na.rm = TRUE)
## 
## Reference: Callaway, Brantly and Pedro H.C. Sant'Anna.  "Difference-in-Differences with Multiple Time Periods." Journal of Econometrics, Vol. 225, No. 2, pp. 200-230, 2021. <https://doi.org/10.1016/j.jeconom.2020.12.001>, <https://arxiv.org/abs/1803.09015> 
## 
## 
## Overall summary of ATT's based on event-study/dynamic aggregation:  
##      ATT    Std. Error     [ 95%  Conf. Int.] 
##  -0.0057        0.0073    -0.0199      0.0085 
## 
## 
## Dynamic Effects:
##  Event time Estimate Std. Error [95% Simult.  Conf. Band] 
##          -7   0.0146     0.0161       -0.0268      0.0560 
##          -6   0.0077     0.0080       -0.0128      0.0282 
##          -5   0.0002     0.0053       -0.0135      0.0139 
##          -4  -0.0022     0.0053       -0.0159      0.0114 
##          -3   0.0055     0.0058       -0.0095      0.0205 
##          -2   0.0043     0.0050       -0.0086      0.0172 
##          -1   0.0105     0.0088       -0.0121      0.0331 
##           0  -0.0002     0.0046       -0.0120      0.0117 
##           1   0.0070     0.0072       -0.0115      0.0254 
##           2   0.0026     0.0094       -0.0216      0.0267 
##           3  -0.0102     0.0112       -0.0391      0.0186 
##           4  -0.0008     0.0104       -0.0275      0.0258 
##           5  -0.0324     0.0187       -0.0805      0.0157 
## ---
## Signif. codes: `*' confidence band does not cover 0
## 
## Control Group:  Never Treated,  Anticipation Periods:  0
## Estimation Method:  Doubly Robust
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(did\_notyettreated\_agg)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## aggte(MP = did_notyettreated, type = "dynamic", na.rm = TRUE)
## 
## Reference: Callaway, Brantly and Pedro H.C. Sant'Anna.  "Difference-in-Differences with Multiple Time Periods." Journal of Econometrics, Vol. 225, No. 2, pp. 200-230, 2021. <https://doi.org/10.1016/j.jeconom.2020.12.001>, <https://arxiv.org/abs/1803.09015> 
## 
## 
## Overall summary of ATT's based on event-study/dynamic aggregation:  
##      ATT    Std. Error     [ 95%  Conf. Int.] 
##  -0.0075        0.0075    -0.0222      0.0072 
## 
## 
## Dynamic Effects:
##  Event time Estimate Std. Error [95% Simult.  Conf. Band] 
##          -7   0.0119     0.0163       -0.0315      0.0554 
##          -6   0.0076     0.0086       -0.0155      0.0307 
##          -5   0.0003     0.0053       -0.0139      0.0146 
##          -4  -0.0054     0.0054       -0.0197      0.0090 
##          -3   0.0034     0.0066       -0.0141      0.0210 
##          -2   0.0020     0.0053       -0.0122      0.0162 
##          -1   0.0080     0.0086       -0.0150      0.0311 
##           0  -0.0032     0.0051       -0.0168      0.0105 
##           1   0.0044     0.0067       -0.0135      0.0223 
##           2  -0.0011     0.0105       -0.0291      0.0268 
##           3  -0.0119     0.0110       -0.0413      0.0174 
##           4  -0.0008     0.0106       -0.0293      0.0276 
##           5  -0.0324     0.0179       -0.0803      0.0155 
## ---
## Signif. codes: `*' confidence band does not cover 0
## 
## Control Group:  Not Yet Treated,  Anticipation Periods:  0
## Estimation Method:  Doubly Robust
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# plot group{-}time ATTs}
\NormalTok{did\_control\_agg\_plt }\OtherTok{\textless{}{-}} \FunctionTok{ggdid}\NormalTok{(did\_control\_agg) }\SpecialCharTok{+}
    \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Group{-}Time ATTs for Control Group"}\NormalTok{, }\AttributeTok{x =} \StringTok{"Time Period"}\NormalTok{, }\AttributeTok{y =} \StringTok{"ATT"}\NormalTok{) }\SpecialCharTok{+}
    \FunctionTok{theme\_bw}\NormalTok{() }\SpecialCharTok{+}
    \FunctionTok{theme}\NormalTok{(}\AttributeTok{axis.text.x =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{angle =} \DecValTok{90}\NormalTok{, }\AttributeTok{vjust =} \FloatTok{0.5}\NormalTok{, }\AttributeTok{hjust =} \DecValTok{1}\NormalTok{))}

\NormalTok{did\_notyettreated\_agg\_plt }\OtherTok{\textless{}{-}} \FunctionTok{ggdid}\NormalTok{(did\_notyettreated\_agg) }\SpecialCharTok{+}
    \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Group{-}Time ATTs for Not Yet Treated Group"}\NormalTok{, }\AttributeTok{x =} \StringTok{"Time Period"}\NormalTok{, }\AttributeTok{y =} \StringTok{"ATT"}\NormalTok{) }\SpecialCharTok{+}
    \FunctionTok{theme\_bw}\NormalTok{() }\SpecialCharTok{+} 
    \FunctionTok{theme}\NormalTok{(}\AttributeTok{axis.text.x =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{angle =} \DecValTok{90}\NormalTok{, }\AttributeTok{vjust =} \FloatTok{0.5}\NormalTok{, }\AttributeTok{hjust =} \DecValTok{1}\NormalTok{))}

\FunctionTok{print}\NormalTok{(did\_control\_agg\_plt)}
\end{Highlighting}
\end{Shaded}

\includegraphics{CSDinDExample_files/figure-latex/unnamed-chunk-7-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(did\_notyettreated\_agg\_plt)}
\end{Highlighting}
\end{Shaded}

\includegraphics{CSDinDExample_files/figure-latex/unnamed-chunk-7-2.pdf}

\subsection{Results of Yearly
Analysis}\label{results-of-yearly-analysis}

\subsubsection{Control Group}\label{control-group-1}

Overall summary of ATT's based on event-study/dynamic aggregation:\\
ATT Std. Error {[} 95\% Conf. Int.{]} -0.0057 0.0071 -0.0195 0.0081

\subsubsection{Not Yet Treated Group}\label{not-yet-treated-group-1}

Overall summary of ATT's based on event-study/dynamic aggregation:\\
ATT Std. Error {[} 95\% Conf. Int.{]} -0.0075 0.0074 -0.0219 0.0069

\end{document}
